In [ ]:
import numpy as np

# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Adjust range as needed
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

Generated 3x4 Matrix:
[[ 2  9 18 16]
 [ 6 19  5  7]
 [14  7 14  6]]

Coefficient Matrix (A):
[[ 2  9 18]
 [ 6 19  5]
 [14  7 14]]

Right-hand Side Vector (b):
[16  7  6]


1. Find the determinant of A, if it is 0 then we cannot solve for x

In [3]:
determinant_A = np.linalg.det(A)

print("\nDeterminant of matrix A:")
determinant_A


Determinant of matrix A:


-3696.0

2. Since det(A)!=0 is true then we can invert the matrix A

In [6]:
x = np.linalg .inv(A)
print("\nSolution for inversed A:")
x


Solution for inversed A:


array([[-0.0625    ,  0.        ,  0.08035714],
       [ 0.00378788,  0.06060606, -0.02651515],
       [ 0.06060606, -0.03030303,  0.004329  ]])

Solution of X

In [8]:
x = np.linalg.inv(A).dot(b)
print("\nSolution for x:")
print(x)



Solution for x:
[-0.51785714  0.32575758  0.78354978]


In [9]:
# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Gaussian Elimination (NumPy):
[-0.51785714  0.32575758  0.78354978]

Verification (Ax = b):
[16.  7.  6.]
