In [45]:
import numpy as np

## Practice no. 1

In [47]:
# Your solution here
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)


Random Matrix:
 [[9 1 3 1]
 [9 5 7 6]
 [1 1 3 5]
 [7 6 7 8]]

Is the random matrix symmetric?  False


## section 2 q2

In [49]:
B = np.array([[10,20,30],[5,10,15],[2,4,6]])
print("Trace: "+ str(np.trace(B)))

Trace: 26


## Practice no. 2

In [51]:
C = np.array([[66,767,5,6,734],
                [56,5,7683,6657,65],
                [7,43,45,234,65],
                [767,8,78,56,32],
                [673,4,23,56,44]])
print("Trace: "+ str(np.trace(C)))

Trace: 216


## Practice no. 3

In [53]:
A = np.array([[1,2,3],[0,4,5],[1,0,6]])
print("Determinant: "+ str(np.linalg.det(A)))

Determinant: 22.000000000000004


## Practice 4

In [55]:
D = np.random.randint(1,20,(3,33))

E = np.random.randint(1,20,(33,3))
print("Product:\n"+str(D.dot(E)))
print("Transpose: "+str((D.dot(E))))
print("Determinant: "+ str(np.linalg.det(D.dot(E))))

Product:
[[3223 3838 3650]
 [3744 4036 3878]
 [3132 3803 3502]]
Transpose: [[3223 3838 3650]
 [3744 4036 3878]
 [3132 3803 3502]]
Determinant: 146790377.99999982


## Practice no. 5

In [64]:
random_matrix = np.random.rand(3, 3)
symmetric_matrix = (random_matrix + random_matrix.T) / 2
is_symmetric = np.allclose(symmetric_matrix, symmetric_matrix.T)
symmetric_matrix, is_symmetric


(array([[0.61229205, 0.43739227, 0.3870848 ],
        [0.43739227, 0.47239343, 0.46917966],
        [0.3870848 , 0.46917966, 0.32262729]]),
 True)