In [29]:
import numpy as np

In [30]:
A = np.array([[1,2,3],[1,2,3]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [1 2 3]]


In [31]:
# 3x3 Zero Matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:")
print(zero_matrix)
# 3x3 Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:")
print(identity_matrix)

Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])
# Matrix Addition
addition_result = B + C
print("B + C:")
print(addition_result)
# Matrix Subtraction
subtraction_result = B - C
print("B - C:")
print(subtraction_result)

B + C:
[[ 6  8]
 [10 12]]
B - C:
[[-4 -4]
 [-4 -4]]


In [33]:
c = np.array([[1,2,3,213,234,56,5,763,667,65],
              [4,5,6,344,546,66,767,5,6,734],
              [7,8,9,45,76,2,46,88,89,45],
              [213,23,443,7,456,434,7,43,8,4],
              [12,43,5,32,546,673,4,23,56,44],
              [243,34,34,43,4,5,56,46,867,99],
              [2,345,7,6,98,7,43,45,234,65],
              [23,43,545,6,5,767,8,78,56,32],
              [345,78,21,34,34,87,23,644,32,65],
              [123,344,543,5,5,667,568,768,45,53]])
b =  np.array([[4,5,6,344,546,66,767,5,6,734],
                [1,2,3,213,234,56,5,7683,6657,65],
                [2,345,7,6,98,7,43,45,234,65],
                [23,43,545,6,5,767,8,78,56,32],
                [12,43,5,32,546,673,4,23,56,44],
              [345,78,21,34,34,87,23,644,32,65],
              [123,344,543,5,5,667,568,768,45,53],
              [7,8,9,45,76,2,46,88,89,45],
               [213,23,443,7,456,434,7,43,8,4],
              [243,34,34,43,4,5,56,46,867,99],])

print("Addition:\n" + str(c+b))
print("Subtraction:\n" + str(c-b))

Addition:
[[   5    7    9  557  780  122  772 7688 6663  799]
 [   5    7    9  557  780  122  772 7688 6663  799]
 [   9  353   16   51  174    9   89  133  323  110]
 [ 236   66  988   13  461 1201   15  121   64   36]
 [  24   86   10   64 1092 1346    8   46  112   88]
 [ 588  112   55   77   38   92   79  690  899  164]
 [ 125  689  550   11  103  674  611  813  279  118]
 [  30   51  554   51   81  769   54  166  145   77]
 [ 558  101  464   41  490  521   30  687   40   69]
 [ 366  378  577   48    9  672  624  814  912  152]]
Subtraction:
[[   -3    -3    -3  -131  -312   -10  -762  7678  6651  -669]
 [    3     3     3   131   312    10   762 -7678 -6651   669]
 [    5  -337     2    39   -22    -5     3    43  -145   -20]
 [  190   -20  -102     1   451  -333    -1   -35   -48   -28]
 [    0     0     0     0     0     0     0     0     0     0]
 [ -102   -44    13     9   -30   -82    33  -598   835    34]
 [ -121     1  -536     1    93  -660  -525  -723   189    12]
 [   

In [34]:
print("Multiplication:\n" + str(np.dot(c,b)))

Multiplication:
[[1515171  243138 3141587  406612 3751826 3234088  411331 1042751  834469
   400874]
 [ 311283  334500  635817   59921  315909 1155507  486837  744117  758051
   156539]
 [  38857   28620   91803   13684   96047  156519   39825  117419  111873
    22366]
 [ 160962  210779   27525  112417  435828  376709  200631  497927  305541
   237864]
 [ 262847   83563   63222   57202  365742  481026   33739  788648  382220
    86548]
 [ 219774   58363  443627  104270  546059  468505  234025  359524  337927
   202966]
 [  75337   30877  134629   84298  246883  221318   35933 2708226 2368530
    40982]
 [ 287272  254277   54426   51933  136500  112393   69316  866428  474573
   112695]
 [  62653   34846   57649  171784  294283  114656  314869  740108  647784
   304666]
 [ 329916  445467  359401  181704  308241  496599  496046 3606236 2579935
   261763]]


In [35]:
print("Element wise:\n" + str(c*b))

Element wise:
[[     4     10     18  73272 127764   3696   3835  38415  39942  47710]
 [     4     10     18  73272 127764   3696   3835  38415  39942  47710]
 [    14   2760     63    270   7448     14   1978   3960  20826   2925]
 [  4899    989 241435     42   2280 332878     56   3354    448    128]
 [   144   1849     25   1024 298116 452929     16    529   3136   1936]
 [ 83835   2652    714   1462    136    435   1288  29624  27744   6435]
 [   246 118680   3801     30    490   4669  24424  34560  10530   3445]
 [   161    344   4905    270    380   1534    368   6864   4984   1440]
 [ 73485   1794   9303    238  15504  37758    161  27692    256    260]
 [ 29889  11696  18462    215     20   3335  31808  35328  39015   5247]]


In [36]:
print("Transpose:\n" + str(c.T))

Transpose:
[[   1    4    7  213   12  243    2   23  345  123]
 [   2    5    8   23   43   34  345   43   78  344]
 [   3    6    9  443    5   34    7  545   21  543]
 [ 213  344   45    7   32   43    6    6   34    5]
 [ 234  546   76  456  546    4   98    5   34    5]
 [  56   66    2  434  673    5    7  767   87  667]
 [   5  767   46    7    4   56   43    8   23  568]
 [7683    5   88   43   23   46   45   78  644  768]
 [6657    6   89    8   56  867  234   56   32   45]
 [  65  734   45    4   44   99   65   32   65   53]]


## 1. Matrix creation and structure - create a 2x3 matrix

In [49]:
mt = np.array([[1,2,3],[4,5,6]])
print(mt)

[[1 2 3]
 [4 5 6]]


## 2. Basic Matrix Operation
- the requirment of the addition is that the two matrices are equal in size while on multiplication, the first matrix's column is the same with the second matrix's row

In [56]:
f = np.array([[56,5,763,667,65],
              [66,767,5,6,734],
              [2,46,88,89,45],
              [456,434,7,43,8],
              [673,4,23,56,44]])
g = np.array([[66,767,5,6,734],
                [56,5,7683,6657,65],
                [7,43,45,234,65],
                [767,8,78,56,32],
                [673,4,23,56,44]])
print("Multiplication:\n"+str(f.dot(g)))
print("Addition:\n"+str(f+g))

Multiplication:
[[ 564651   81382  126551  253155  115228]
 [ 545927   57656 5910766 5148925  131112]
 [ 101872    6440  365365  334330   15006]
 [  92814  352599 3340555 2896368  365097]
 [ 117367  517824   40512   41648  499465]]
Addition:
[[ 122  772  768  673  799]
 [ 122  772 7688 6663  799]
 [   9   89  133  323  110]
 [1223  442   85   99   40]
 [1346    8   46  112   88]]


## 3. Transpose of Matrix
Transpose matrix will turn the column into rows vice versa
For example in 3x2 matrix, the size of the matrix will turn in a 2x3 matrix

In [59]:
mt = np.array([[1,2,3],[4,5,6]])
print("Normal 3x2 matrix:\n"+ str(mt))
print("Transposed 3x2 matrix:\n"+ str(mt.T))

Normal 3x2 matrix:
[[1 2 3]
 [4 5 6]]
Transposed 3x2 matrix:
[[1 4]
 [2 5]
 [3 6]]


## 4. Working with Large Matrices

In [66]:

print("Sum of matrix: "+str(np.sum(f)))
print("Transposed matrix:\n"+str(f.T))

Sum of matrix: 5152
Transposed matrix:
[[ 56  66   2 456 673]
 [  5 767  46 434   4]
 [763   5  88   7  23]
 [667   6  89  43  56]
 [ 65 734  45   8  44]]


## 5. 

In [69]:
D = np.array([[1,2,3,213,234,56,5,763,667,65],
              [4,5,6,344,546,66,767,5,6,734],
              [7,8,9,45,76,2,46,88,89,45],
              [213,23,443,7,456,434,7,43,8,4],
              [12,43,5,32,546,673,4,23,56,44],
              [243,34,34,43,4,5,56,46,867,99],
              [2,345,7,6,98,7,43,45,234,65],
              [23,43,545,6,5,767,8,78,56,32],
              [345,78,21,34,34,87,23,644,32,65],
              [123,344,543,5,5,667,568,768,45,53]])
E =  np.array([[4,5,6,344,546,66,767,5,6,734],
                [1,2,3,213,234,56,5,7683,6657,65],
                [2,345,7,6,98,7,43,45,234,65],
                [23,43,545,6,5,767,8,78,56,32],
                [12,43,5,32,546,673,4,23,56,44],
              [345,78,21,34,34,87,23,644,32,65],
              [123,344,543,5,5,667,568,768,45,53],
              [7,8,9,45,76,2,46,88,89,45],
               [213,23,443,7,456,434,7,43,8,4],
              [243,34,34,43,4,5,56,46,867,99],])

print("a. "+ str(D+E))
print("b. "+ str(E-D))
print("c. "+ str(D.dot(E)))

a. [[   5    7    9  557  780  122  772  768  673  799]
 [   5    7    9  557  780  122  772 7688 6663  799]
 [   9  353   16   51  174    9   89  133  323  110]
 [ 236   66  988   13  461 1201   15  121   64   36]
 [  24   86   10   64 1092 1346    8   46  112   88]
 [ 588  112   55   77   38   92   79  690  899  164]
 [ 125  689  550   11  103  674  611  813  279  118]
 [  30   51  554   51   81  769   54  166  145   77]
 [ 558  101  464   41  490  521   30  687   40   69]
 [ 366  378  577   48    9  672  624  814  912  152]]
b. [[   3    3    3  131  312   10  762 -758 -661  669]
 [  -3   -3   -3 -131 -312  -10 -762 7678 6651 -669]
 [  -5  337   -2  -39   22    5   -3  -43  145   20]
 [-190   20  102   -1 -451  333    1   35   48   28]
 [   0    0    0    0    0    0    0    0    0    0]
 [ 102   44  -13   -9   30   82  -33  598 -835  -34]
 [ 121   -1  536   -1  -93  660  525  723 -189  -12]
 [ -16  -35 -536   39   71 -765   38   10   33   13]
 [-132  -55  422  -27  422  347  -16 -6

The matrix operation that can be applied in Computer Science is all of it. Because the basic operation of the matrix can be used in the GPU or Graphical Processing Unit. The calculation of graphics requires matrices. And when solving matrixes we need GPU. Why use GPU instead of CPU, CPU can handle small process but fast and the GPU is the opposite of CPU. In GPU, there is a CUDA cores that are responsible for the process. GPU can handle multiple process via matrix computations, like all processes are working in paralell.