In [40]:
import numpy as np

# Practice

## Problem no. 1

In [43]:
#Create a square matrix
b = np.array([[3, 4],[2,5]])

#Check whether the determinant is 0 or not
if np.linalg.det(b) != 0:
    #Store the value of the inversed matrix
    x = np.linalg.inv(b)

    #print the matrix
    print("The inverse of matrix b is: \n")
    print(x)
else:
    #Print this statement when the first condition didn't meet
    print("Matrix b is not invertible, no unique solution.")

The inverse of matrix b is: 

[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


## Problem no. 2

In [45]:
#Create a coefficient matrix and a constant vector matrix
a = np.array([[2,3],[4,-1]])
b = np.array([7,5])

#Check whether the determinant of the coefficient matrix is 0 or not
if np.linalg.det(a) != 0:
    #Store the value of the vector of the unknowns matrix
    x = np.linalg.inv(a).dot(b)
    
    #print the matrix
    print(x)
else:
    #Print this statement when the first condition didn't meet
    print("Matrix a is not invertible, no unique solution.")



[1.57142857 1.28571429]


## Problem no. 3

In [47]:
#Create a square matrix
a = np.array([[1,2,3],[0,1,4],[5,6,0]])

#Check whether the determinant of the matrix is 0 or not
if np.linalg.det(a) != 0:
    #Store the inversed matrix
    x = np.linalg.inv(a)

    #Print the inversed matrix
    print(x)
else:
    #Print this statement when the first condition didn't meet
    print("Matrix a is not invertible, no unique solution.")

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


## Problem no. 4

In [49]:
#Create a coefficient matrix and a constant vector matrix
a = np.array([[1,1,1],[2,5,1],[2,3,8]])
b = np.array([6,-4,9])

#Check whether the determinant of the coefficient matrix is 0 or not
if np.linalg.det(a) != 0:
    #Store the value of the vector of the unknowns matrix
    x = np.linalg.inv(a).dot(b)

    #print the value of the vector of the unknowns matrix
    print(x)
else:
    #Print this statement when the first condition didn't meet
    print("Matrix a is not invertible, no unique solution.")

[10.84210526 -5.21052632  0.36842105]


## Problem no. 5

In [51]:
#Create a coefficient matrix and a constant vector matrix
a = np.array([[4,-1,0],[3,5,2],[-2,4,1]])
b = np.array([5,6,2])
if np.linalg.det(a) != 0:
    x = np.linalg.inv(a).dot(b)
    print(x)
else:
    #Print this statement when the first condition didn't meet
    print("Matrix a is not invertible, no unique solution.")

[  2.6   5.4 -14.4]


## Bonus challenge

In [53]:
def inverseMatrixChecker(x, y):
    if np.linalg.det(a) != 0:
        x = np.linalg.inv(a).dot(b)
        print(x)
    else:
        #Print this statement when the first condition didn't meet
        print("Matrix a is not invertible, no unique solution.")


a = np.array([[4,-1,0],[3,5,2],[-2,4,1]])
b = np.array([5,6,2])
inverseMatrixChecker(a,b)
a = np.array([[1,2,3],[2,4,6],[3,6,9]])
b = np.array([5,6,2])
inverseMatrixChecker(a,b)

[  2.6   5.4 -14.4]
Matrix a is not invertible, no unique solution.
